# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeterminedAgent < Formula
  desc ""
  homepage "https://github.com/determined-ai/determined"
  version "0.19.11"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/determined-ai/determined/releases/download/0.19.11/determined-agent_0.19.11_darwin_arm64.tar.gz"
      sha256 "51d7a553fa6cef2dd9c8466a4daa5d6efaadb0e15e9150d647f2c9e6f319b703"

      def install
        bin.install "determined-agent"

        doc.install "LICENSE"

        (var/"log/determined").mkpath

        (etc/"determined").mkpath
        inreplace "etc/determined/agent.yaml" do |s|
          s.gsub! "# master_host: 0.0.0.0", "master_host: 127.0.0.1"
          s.gsub! "# master_port: 80", "master_port: 8080"
        end

        Pathname("etc/determined/agent.yaml").append_lines <<~EOS
          container_master_host: host.docker.internal
        EOS

        etc.install "etc/determined/agent.yaml" => "determined/agent.yaml"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/determined-ai/determined/releases/download/0.19.11/determined-agent_0.19.11_darwin_amd64.tar.gz"
      sha256 "d93e55763d68e4d8744f9ab5b93baaf53d81079147978566118224d9667d3f44"

      def install
        bin.install "determined-agent"

        doc.install "LICENSE"

        (var/"log/determined").mkpath

        (etc/"determined").mkpath
        inreplace "etc/determined/agent.yaml" do |s|
          s.gsub! "# master_host: 0.0.0.0", "master_host: 127.0.0.1"
          s.gsub! "# master_port: 80", "master_port: 8080"
        end

        Pathname("etc/determined/agent.yaml").append_lines <<~EOS
          container_master_host: host.docker.internal
        EOS

        etc.install "etc/determined/agent.yaml" => "determined/agent.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/determined-ai/determined/releases/download/0.19.11/determined-agent_0.19.11_linux_amd64.tar.gz"
      sha256 "6de993c51a4c97374f0b436014915ed50a5d9b23f832c6d4e3162fa4c361344e"

      def install
        bin.install "determined-agent"

        doc.install "LICENSE"

        (var/"log/determined").mkpath

        (etc/"determined").mkpath
        inreplace "etc/determined/agent.yaml" do |s|
          s.gsub! "# master_host: 0.0.0.0", "master_host: 127.0.0.1"
          s.gsub! "# master_port: 80", "master_port: 8080"
        end

        Pathname("etc/determined/agent.yaml").append_lines <<~EOS
          container_master_host: host.docker.internal
        EOS

        etc.install "etc/determined/agent.yaml" => "determined/agent.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/determined-ai/determined/releases/download/0.19.11/determined-agent_0.19.11_linux_arm64.tar.gz"
      sha256 "4eb6c29ca2428cc0bd152a7f5898eeb2aee1b93c159533caff064f7fb9ae00f6"

      def install
        bin.install "determined-agent"

        doc.install "LICENSE"

        (var/"log/determined").mkpath

        (etc/"determined").mkpath
        inreplace "etc/determined/agent.yaml" do |s|
          s.gsub! "# master_host: 0.0.0.0", "master_host: 127.0.0.1"
          s.gsub! "# master_port: 80", "master_port: 8080"
        end

        Pathname("etc/determined/agent.yaml").append_lines <<~EOS
          container_master_host: host.docker.internal
        EOS

        etc.install "etc/determined/agent.yaml" => "determined/agent.yaml"
      end
    end
  end

  def caveats
    <<~EOS
      Determined agent config is located at #{etc}/determined/agent.yaml
    EOS
  end

  service do
    run [opt_bin/"determined-agent", "--config-file", etc/"determined/agent.yaml"]
    keep_alive false
    error_log_path var/"log/determined/agent-stderr.log"
    log_path var/"log/determined/agent-stdout.log"
  end
end
