# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeterminedAgent < Formula
  desc ""
  homepage "https://github.com/determined-ai/determined"
  version "0.26.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/determined-ai/determined/releases/download/0.26.7/determined-agent_0.26.7_darwin_arm64.tar.gz"
      sha256 "dc5f6fac692a2e1fb6790f8059788d4c07b3d7cb42f382a2dfa12d20efce24ec"

      def install
        bin.install "determined-agent"

        doc.install "LICENSE"

        (var/"log/determined").mkpath

        (etc/"determined").mkpath
        inreplace "etc/determined/agent.yaml" do |s|
          s.gsub! "# master_host: 0.0.0.0", "master_host: 127.0.0.1"
          s.gsub! "# master_port: 80", "master_port: 8080"
        end

        Pathname("etc/determined/agent.yaml").append_lines <<~EOS
          container_master_host: host.docker.internal
        EOS

        etc.install "etc/determined/agent.yaml" => "determined/agent.yaml"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/determined-ai/determined/releases/download/0.26.7/determined-agent_0.26.7_darwin_amd64.tar.gz"
      sha256 "a7d55a03bd25d172af6e71e0b91843c77cec69da0665794a91fe4e3d1223ab15"

      def install
        bin.install "determined-agent"

        doc.install "LICENSE"

        (var/"log/determined").mkpath

        (etc/"determined").mkpath
        inreplace "etc/determined/agent.yaml" do |s|
          s.gsub! "# master_host: 0.0.0.0", "master_host: 127.0.0.1"
          s.gsub! "# master_port: 80", "master_port: 8080"
        end

        Pathname("etc/determined/agent.yaml").append_lines <<~EOS
          container_master_host: host.docker.internal
        EOS

        etc.install "etc/determined/agent.yaml" => "determined/agent.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/determined-ai/determined/releases/download/0.26.7/determined-agent_0.26.7_linux_arm64.tar.gz"
      sha256 "eaa270629aabddcdb150400baeab90f868059affda5e87c2d4bed904f6651224"

      def install
        bin.install "determined-agent"

        doc.install "LICENSE"

        (var/"log/determined").mkpath

        (etc/"determined").mkpath
        inreplace "etc/determined/agent.yaml" do |s|
          s.gsub! "# master_host: 0.0.0.0", "master_host: 127.0.0.1"
          s.gsub! "# master_port: 80", "master_port: 8080"
        end

        Pathname("etc/determined/agent.yaml").append_lines <<~EOS
          container_master_host: host.docker.internal
        EOS

        etc.install "etc/determined/agent.yaml" => "determined/agent.yaml"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/determined-ai/determined/releases/download/0.26.7/determined-agent_0.26.7_linux_amd64.tar.gz"
      sha256 "f0662e6c842aa00dca308eab5022bcdde1268cb0c081ceaa6bfbebededcfe1d2"

      def install
        bin.install "determined-agent"

        doc.install "LICENSE"

        (var/"log/determined").mkpath

        (etc/"determined").mkpath
        inreplace "etc/determined/agent.yaml" do |s|
          s.gsub! "# master_host: 0.0.0.0", "master_host: 127.0.0.1"
          s.gsub! "# master_port: 80", "master_port: 8080"
        end

        Pathname("etc/determined/agent.yaml").append_lines <<~EOS
          container_master_host: host.docker.internal
        EOS

        etc.install "etc/determined/agent.yaml" => "determined/agent.yaml"
      end
    end
  end

  def caveats
    <<~EOS
      Determined agent config is located at #{etc}/determined/agent.yaml
    EOS
  end

  service do
    run [opt_bin/"determined-agent", "--config-file", etc/"determined/agent.yaml"]
    keep_alive false
    error_log_path var/"log/determined/agent-stderr.log"
    log_path var/"log/determined/agent-stdout.log"
  end
end
